gedbrowser:
    home: /var/lib/gedbrowser

logging:
    level:
        org:
            schoellerfamily: WARN
            springframework:
                test: WARN
                core: WARN
                beans: WARN
                data:
                    mongodb:
                        core:
                            index: OFF

spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true

geoservice:
    keyfile: /var/lib/gedbrowser/google-geocoding-key
    backupfile: /var/lib/gedbrowser/geoservice-backup.json

management:
    port: 8081
    security:
        enabled: false
