engines:
#  stylelint:
#    enabled: true
  markdownlint:
    enabled: true
    code_blocks: false
    tables: false
    br_spaces: 3
  fixme:
    enabled: true
    config:
      string:
      - FIXME
      - TODO
      - NOPMD
  checkstyle:
    enabled: true
    channel: "beta"
    config: config/checkstyle.xml
  pmd:
    enabled: true
    channel: "beta"
    config: config/pmd.xml
ratings:
  paths:
  - "**.css"
  - "**.java"
  - "**.md"
  - "**.html"
exclude_paths:
- config/
