version: "2"
checks:
  similar-code:
    enabled: false
  identical-code:
    config:
      threshold: 30
  return-statements:
    enabled: false
engines:
#  stylelint:
#    enabled: true
  markdownlint:
    enabled: true
  fixme:
    enabled: true
    config:
      string:
      - FIXME
      - TODO
      - NOPMD
  checkstyle:
    enabled: true
    channel: "beta"
    config: config/checkstyle.xml
  pmd:
    enabled: true
    channel: "beta"
    config: config/pmd.xml
ratings:
  paths:
  - "**.css"
  - "**.java"
  - "**.md"
  - "**.html"
exclude_patterns:
- "config/"
- "**/src/test/"
