engines:
#  csslint:
#    enabled: true
#  fixme:
#    enabled: true
  checkstyle:
    enabled: true
    channel: "beta"
    config: config/checkstyle.xml
  pmd:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.css"
  - "**.java"
exclude_paths:
- config/
