engines:
#  stylelint:
#    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD009:
        br_spaces: 3
      MD013:
        code_blocks: false
        tables: false
  fixme:
    enabled: true
    config:
      string:
      - FIXME
      - TODO
      - NOPMD
  checkstyle:
    enabled: true
    channel: "beta"
    config: config/checkstyle.xml
  pmd:
    enabled: true
    channel: "beta"
    config: config/pmd.xml
ratings:
  paths:
  - "**.css"
  - "**.java"
  - "**.md"
  - "**.html"
exclude_paths:
- config/
