engines:
#  csslint:
#    enabled: true
  fixme:
    enabled: true
    config:
      string:
      - FIXME
      - TODO
      - NOPMD
  checkstyle:
    enabled: true
    channel: "beta"
    config: config/checkstyle.xml
  pmd:
    enabled: true
    channel: "beta"
    config: config/pmd.xml
ratings:
  paths:
  - "**.css"
  - "**.java"
exclude_paths:
- config/
