language: java

services:
  - docker

addons:
  firefox: "49.0.2"
  sauce_connect:
    username: dickschoeller
  jwt:
    secure: "SCAjXGKQ5p6fZj38LFzYBursOm8HSNwkEHhbMQa8uVmRoH9lSzjr6HdeZLUFRUgKlttoI5xH21bo7ysw2Tshn6fvIZHnoWid23OniZF87aUs3OnwCGB5/vwFgU4K48juoDgJXc0IpgfH7rj8t5yCUEpP1jst3LJGmyTbUfOBSbzROS4UufwsKZdKNKXJbGN21d8q7dpAjUjD8OUgK834Nkj/973DiOVUcFBpF1FFf02yFDj0XJJITFiABDLEhZ1SgolKXCWRoFTruZKO3+OnycaZUUsICmuOj/3L7Aq1qQcUczJYZq0kCEHY6tQlXQrjepSGCh21GmuBCHHnMso8YMiC9szqVeAbP8/aFXCitlvw5q6Zw1GpHuk0bBwWJsZU5n2HTpTUKpMwGFGcdg3AQ6dFjwCpig3+D1HZJkHYaJRLN3qVQmtNRyiLwcr9F2RQEqtqN9yOvj5iiohFE+7pLMgpy+6rj+36XTYaJlQRZLGbQPhaiznlpz/B4XrjbttNgZZPOfIy05L/rh6L/TpeaKkbrJReOuz0iut3qeoqPE6bIJ5FJ5Tu5MR2WiRf8CYkasxfA89kjCEvpqMt6ujBtil7A0ZO9f+koIJvjZlXHq02XvBKf34ZLj/yjf209FPe7Gdz6uVQzOTGMqiWOSs0G//9cC33cwQzk1mMnK3TckU="

env:
  global:
    # REPOTOKEN
    - secure: "nqpQ1c4b74dd15/eSZBb02QE3HS4Hq/3cPdzUAtKNWErHALkWjRXa6VvrjO9F30G+2TGm/cdK6tX2lp1PPYeUnR8eEwxbTSw1czw/Dzc/RvggbIek/fTn3O6ihUXESY+rbRhRMyGlQ7vPmQKo0f0dMjv33SsKfHxL3jtlbFUnJSFFxhGgDCe54akTMZyCGBiYYnQZKOWWhKAFTS1kT8Um+/l2fZo1LTmLSfr8aJF1irDLfvAbtV3DKsJwgnt7um/PqYOBXK+6XaZ7P6Zo7nd5qS+ZNm2WzgTnHETNSvDRAzAyUydJHorf52MsmNiLSb3qQdWluk+9vewWVs61qPMH9pZPTlS8wgCcyJ3jceTlG9HM1dREALhXXHFoCmKUX9DgWHxREuSy/88gTVKg5qiRTVo/UXE5BrsXb08AawXi8IM4yuQHJxfTcuIv05+CsbzHqyysUQkwSVXA7wYjEMJ3WhY2p0ss0Oxohu5JHQZ1YYByO0xg4Hrm0eTLWsnq9ZTnfoT4MpATX8h73grSWe4mSmIVmqcs2egEwLolmTBD5lFRaQum7N3+SZ66dVwT1H3fgqhne1wuMPWwAWVVdZY3l0fxZoR7qD6WbO7BUwo0F4fSIo9RFgcQUKtx+jWJ9Bgql5th9prc3wuJuSdUHOe6hmcDyfsSi8BMoB2jZP4Hcs="
    # GPG_PASSPHRASE
    - secure: "bxrzTYVeLpxKcO37OTVBKlNgny2rE1A4B2/Yw5I/OnO0iS1hl3kIcIPw07LUXG83HGMpkK/xncIoG6UQgKZWHHLYKKSC9H0QIg9sb+catrlSGp6JHdga/Xa2prbcdw1CxvPphGm0FUSa8ZhsFJvSBgealGLkEZvnhUbHVhdx+TmL2DLAPdX1dUGoZvhOGYmjwcsRpKwbV4ByOo27A7uwdVSTSBJb0rU9Wef4yX5/RGODTxp0GRSIlHmzaRcnLACAsYVO5Wikb7o/Yg3l3mV56a2qwt7SKCTbeAWhi1hOb+GsJOCNvnCIZP2IBh+L3h9nYjheavzmhhZ+yKUAfr5Lh1by0wgEHHXZVvzfpRePBLDuw5v8zXcR1B8EeMVWv5bia+nOpkfbiGW6l3h1QO+6QSI6KT9MVy1GCALPMYQ47HMEOReNMNyz6MPiqMU7sZXP9HVS9LYZNCIPA5qIfKXQ55VyzGqqJWRw4B92kZp+No+O22A9m/hh8H2aRzNYRiJqDQf8l2bidq6vGqFSZp2/P8rXaCaCuKdo+tIfbxvTdZb7fznnY8UewVYT9dXgbUHUx9kGPTOarMjmrcH9wxaBFqR3DRSQPceZlQ7ZR9itJq4c5CxVRH2GZIOCNb7SmmQBAe4970EzvFVL1Xv/PT8Q7MEhUER+Oi5AAj2CmTQ13PU="
    # GPG_KEY_NAME
    - secure: "KVpOHU7Oy44evUDdcWwWvNWWf2EvWQBeC5xcEiObCPz09U8tKRz8pX8bqwM1B8kFrXBNfrALFVkpgkqbb0pVuWbrKjqXKby+r05JR2pe0wPp/228nrNaRyD2OoruvF1+AJyWquS2CiDt68MkfNF6eJNcptYDMZnv8Nr2vb+hZkUn10Fqek9NvWnAsWTjPANZdpQjPrHHScRvLVadkCMubYr6WA+CSptBwYw+Tc9/Qgm0FZPsnDH82zD79JIKRQlorTedwZ1HxRwKFuwL1R1FgQXGIEFXgkT9N4E+93pF6QoeKacRrJWEt8Pq52dWpBqvT/mECkSPQ4swtVpoFU2NboBrtDcTyndH9yDfk0Xl6ASBSuV1KLUF4fF2My4Pv+HhB4j9TayrHkOkxSVdBJFNuo/UTProj4RxfGd4Zjca1ia9rHTYViAfX6syM2yrG0/Sx1tdHoDaZtmm54eJBxYqmCZnzw2ve69heIgdgBuy5U5qJPeJw+KMZx57yPEUpz1tgOk8KufAFB1k3S/AkBrnBPEhxY5+ls0GR2hVZwNwUi5CHcfKv5VkMQs2yyYmqM/rDu7ls0FmeOkFVOFnojM2dEyvOnegMkpJRlEAhIjRg7GtiTRQSZArohxFqWGxJUS6JscxaUlP6VklHcI5IwlFCI47G2ZsvUHxpj40J+0taGA="
    # DOCKERUSER
    - secure: "oWjizEIkmJeJl2JSe7KcbB4+Fhz5UPs7agqOuh2nU+3RE60YE7HkCGKhmWYfz4jhl2bvC1KKeK1YfhZCeHtU5dBhYtipQRmrfc46vuqSR0DjTR6TuE4YhhHGjBrlkdSX/wx9zjidp51ZIC/p0ne3YL0Ehgo6Mm4WRzkrz69Ka8vg1G44gf5Tkw9ZDvYrLt7tDSxOWRzXc6sOnf5JxH+2VBPrYF544DVXdylHMewVDGvOXAb+8Xvmb6JHqkjinTtJK7bzV9gMau/SRPea03ticy6rksh4aC9LTU2GsRkAbVd6xtD135kbaMexj4Z66RaxMvZy4rP9EpgRbfSD9Rc/gO2N2JBxFK2q2aZNxQOOx4fUM4RMm1YSpovL7ENuYRzVmaBZxMF6BOxIzZFmUo8pv6IJkO9NpV6PczbVwl8WX7TcK87l4g0NbbzV0mM95LS4rYF8Xii4MN2EVFaURzjae8vE+IknWyaeK+P+V+0iC0PcNN4+jPffN8UC1oQ4zu8KGN5oZAQtuCtmRFiXaIEvHrfxXXc5COc6yBNCtBPZP/LsXBcbdX172bu0jpSAcPOfCiKJ/CT7+1KtVE0EKnuMpDYegPOSAAIRROd9Brn7bKWhsFDtftr8hNY7nVEBDKiIPZxbCEzXgLRzv0x9UymqVXYPBBHHTVaSrzcDk5TQ00A="
    # DOCKERPASS
    - secure: "C0bDP7SoCRKAg45ZdUQOJjGshwsZZVHOgCO/IH/6lkGbFfIVeUPhaaEivyMvzB58lwNzvyYVu7db/FblddNj1PDETq/XIhK3N+8k5egSsBeL1WTrxDVJQTucVMBEsudz9+QYu6Ieelowyxma5aN9m1dKMwzv0IiGDw6TZgnZA0wOALk+UQeXBgCATaDkEm2uPzaKnG/g2V6tqSghB1SbrvmvFOn5xEqyvxHZxJ5cdpnto2QiIfhFH4vBscQwUAltTupi1A+pTQF2IrKEVL5YGXB6E0IexOWzpuhk7pN2SbkepM0ZPzaKIDGplkt3eoj7GafHWgbOgSJeBr7SD2JKkSW8UgM3Afd7hilF+qdvbC8btMIhS2E7tiuHL1vQg0BZbwYkjWtet/y5hU3asFId5aluZXToCLBKm8WO8BZcAeVq+OwgXsLzFbldVQdhWTNiOOiWsqKLmqfdF680Ma0eU3bY5YXLhK7+pv2gZH54FwnrV5k8TN/qDK81qz/k8sJj0fXMxgPLMa0i9f3QL9WuWBBE30il5XMwugE7CZH8w+p6wOiEtqSX6B6+uSvZw+LMMnMfC9Bqwwsvg3oW6dug0Vd1AuKbY7VQOf1idDJ/xsjvCcjr4Hv5wBQYDGbEmqhMgUKFaqYCxvUlMzabEh0srxXw2DeY5OLznADhqbEeEe8="
    # OSSRH_USER
    - secure: "I7kpYvDzSW8c/aitLg+xrTSTihCEmravYKiBHQd5uEfLUq4iF59jAntYyQZWiO2Hr4GjeVekq6XpMBloddcyfg9RIXWh36BZ6v+1HOTNaA1GqjDLFjGdNBX8zgp1M0tCKor3xM00rMn9XvUcJIYRX3DkPLCefzsoBum4XZEhcVWxppClz1fHgJ/m4Wuc9IX47XWjXOiWha5ACM0osTXgNGEcDDtXDxZV3L+WPeNurATURiKXaCSlYOVIvpVHYAMLga4IT65ia3croRA37+EksRunt5rlhm5F0q9h/GtgCDdUVCl6sRFlq2xjzq5Ff3EpE+p0NWOH/vcvxc6Nre/+qDtoqHbw2Vc9lmnGYw+LUuboGY3hnmbDsqpi1C3aklNPlLgjldQKQ75bi6iWwyFcQ1Gp0+WoQ84qH1xV+HtEcPi8W5HBnD+vyi3RveL44FJ9ttXFwzymmWbgGGNaTwePl+hhwcXp3jYpnAfvlp9pgsKmMnw12g+8WBd5c3NbKCX85NFbKpa3aTp5x5RbfYsmar+qqf1FreiXM0B5noksca1FG0iQCRlTQIwLcQRjQc9AX4MkSPCvu9rrP9vToIBFITjgIaVjZEknf3eNkNjGD96fS1im+56+So5wJmpASPJnVbIJM6Fui+VMZAF4jhUgOi7In7zwDgALKr0oFSbxs44="
    # OSSRH_PASS
    - secure: "QcYMf74iQ//5ahvbXcWqvj0pHz4RtvH/gZWV+uBuhDsuxGDjC6I0jN0X2ew35c2KR1gQJz1jXwxkveU1PH3NNgeq0dOOI7teMDkuULrVaptMzzjU6puJPreq3GCRVE6LSWeSObBfpSfAbGfzoeagXOuUR8wmgh73nKr0vyVPM6QdDewmbdMiSfIYRYRWw+bmMENqn9roehYEHX90L8ac1JSiMaxKkDdL1WFaL3o/9IwrTN9vIXYbklRny8s1Qa81cYHWEO/3jaDEuniDcZ9tw6hH2J0POjewh1cEZwmYbc2H4IGkqLCays7zqqjP7YT9W6JKY2cWLtdTD35Lgr4nOZ8Ned8gzoX2PjuZDi60wv0pddpstic6T8XK/YDd7tnJD0lzSFhOu8auaXpn93UZiroamN1ajW5SHfnmEXt6Dg8coF1/JmXEZfbPaU68LDdcnN8vep5m7mNaS83DlhIyircH95+iPWXyOe+FAW9sOXurc2NnJF4DgMHvcmHosWQtGIuItpnsIyXyfb/ZzKullJ9jLeF+MesCCLy8IFzCBYWf2BKMiNC76OOeE8QLtXi8rFPlQzy1545cvTIPC5nz/pWRwyZ2Vh/cFQILiu/Px0wj1B73TSsH+Neqoyuf9AqeV6ysjYylPys9TcBbmGwz8Yrg4jHFeeFFfkTB+xQRW3k="
    # GOOGLE_GEOCODING_KEY
    - secure: "vVh1Gab3sJdoAh+RZrRYbz8XlGCPX3WVvVSuqyRsMdKt1HT2ZJsOzshLDdnUeOGlkwZp+NQcvR3oB1MyFwj6DO92hxETl2eW+AXRMR9ZV09Rhsvg/ZfnR7FZIuo/tV6XtNLHucLqKgGWuETzmsmTlObor4Ovr4nRpwibU7qCQJUinAlEDh5F9Nt1Nl2+2yqdPAzUdht56RlRMhdBR9vFjDK6cRj75QtrBt2r9GjCnM0fdCTX/5/zBiDQ0dsrhFl1sWNASmRjKJHuidGCmwjIa87Fn1I1CZXIutxQ3iGIKKKQYOJQ+kXqfUMaX76nE+LJqQtNle4HrkzYN/OO2xECiqN4boJjf0GsufscAurJG2eOWVhbfB0nxqPyMU7zg9MdJ46jm6mQ4vRwSfu6iuoBB944rhRO+JHcUAf08D5/F//tmus6H9RCOqneSGmkqpYFAWSPnm+I4aOLzxk2IXyoPDl45VPBXEMo+VSSveGJ2aEjdYbLm4hDxvhy/rvIhJwhp59NnNEJHV2AAtyriL4f4dDTfa6uw7TzjdA6qU0SxskH0YJ0Ixp0bauRwQf3r4Vs6BdGvp11gtJvvRM0eHUYKIRue/Nl0YOWhM2kJH+3BNufkqkxddTHZE/2T7rPFvk9dNmp+VOQAZWX+ceV757jxj9XyrHZO9BEeGs5DvI7clM="
    # GOOGLE_MAPPING_KEY
    - secure: "sMdtSxE1udkKi1DQOEnMW/WG5HCXEieHzVuyRwdA6dnTHb5IQEDkv/cVpBQ/m+ufEcg/mezNHK+P1kWbs/Nynv17CdxTxOZYTRCtLKeAMl7ev7B36eEwoqfmyCyPbjeVHbljatJKSYKBjKluzTMFbsSonrQosoHMF30ynFRRYoF5EVKt1FSc2K+RZR29u1fzSAsqFLPAl7hq8uO2BVspNUBj5vDL93WWidZ941Su1M1l+LDlj0ZYeHAdrsjRdO88l2ElPdbaQzHFewF+gjbC8Tm+OkKuio+Z9I9/6WJ4fZsnPQNtX2n8CysvxUDB6glk9RRZV5bfsJbE0Yig3ckY4IBWgBopk6IiGgiV7i3F9HxsSz1Vim6EEjar3BUVGc3D03K5bHxafIdxroq7x8e/8GzmojFREdcxKKbKCpvv8s5pVczIE5yNLVpatrKZOc7uMMuK6JqK1vzL4U5Cm1Xr4d4njy73+Fxt8iI4AyJZoHn11PTlkR9mPHT/0gb3IKFSvuLomKQXU/lE46tGTH/OephCJM+alIKBI+7ORoIKspfCL4Q2Gh4XbSnkO7eya9UqpLjqoFja1ms8Mxa2YMM5KL9WOmGJBbu8JRRYzQF/kQcOxrH3bOua8MYjXMNCGeGrDL6/X6KDLgkTiwEndOHzw+TDjid6dY3OHGPq8CwMkXk="

before_install:
  - mkdir /home/travis/data
  - mkdir /home/travis/gedbrowser
  - cp $(find . -name 'gl120368.ged' | head -n 1) /home/travis/gedbrowser
  - cp $(find . -name 'testUserFile.csv' | head -n 1) /home/travis/gedbrowser
  - echo $GOOGLE_GEOCODING_KEY > /home/travis/gedbrowser/google-geocoding-key
  - echo $GOOGLE_MAPPING_KEY >> /home/travis/gedbrowser/google-geocoding-key
  - docker run -v /home/travis/data:/data/db --name mongo -p 28001:27017 -d mongo

install: mvn install --settings=config/settings.xml -Pinstall -Dskip.integration.tests=true -B -V
# > /dev/null 2>&1

jdk:
  - oraclejdk8

before_script:
  - docker ps --all

script:
  - mvn --batch-mode install jacoco:report coveralls:report -Dspring.data.mongodb.port=28001 -Dgeoservice.keyfile=stub -Dgeoservice.backupfile=/home/travis/gedbrowser/geoservice-test-backup.json -Dgedbrowser.home=/home/travis/gedbrowser -DrepoToken=${REPOTOKEN} --settings=config/settings.xml
  - ./config/docker-shakedown.sh
  - ./config/before-deploy.sh
  - ./config/deploy.sh
  - cd gedbrowser
  - mvn integration-test --settings=../config/settings.xml -Pintegration-test -DprintNavigation=true -Dselenium.browser.name=htmlunit
  - mvn integration-test --settings=../config/settings.xml -Pintegration-test -DprintNavigation=true -Dselenium.browser.name=chrome
  - mvn integration-test --settings=../config/settings.xml -Pintegration-test -DprintNavigation=true -Dselenium.browser.name=firefox -Dselenium.platform=linux
  - mvn integration-test --settings=../config/settings.xml -Pintegration-test -DprintNavigation=true -Dselenium.browser.name=edge -Dselenium.platform=windows

#after_success:
#  - ./config/docker-shakedown.sh
#  - ./config/before-deploy.sh
#  - ./config/deploy.sh
#  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
#  - mkdir -p /home/travis/bin
#  - unzip chromedriver_linux64.zip -d /home/travis/bin/
#  - sudo apt-get update
#  - sudo apt-get install -y libappindicator1 fonts-liberation
#  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#  - sudo dpkg -i google-chrome*.deb
#  - which google-chrome
#  - export CHROME_DRIVER=/home/travis/bin/chromedriver
#  - export CHROME_BIN=/usr/bin/google-chrome
#  # - export CHROME="-Dwebdriver.chrome.driver=${CHROME_DRIVER} -Dchrome.binary=${CHROME_BIN}"
#  - wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
#  - tar -xzf geckodriver-v0.14.0-linux64.tar.gz -C /home/travis/bin
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3
#  - ps -ef | grep -i xvfb
#  - cd gedbrowser-selenium
#  - mvn integration-test --settings=../config/settings.xml -Pintegration-test -Dselenium.port=8080 -DprintNavigation=true ${CHROME}
