language: java

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -DskipDocker -B -V

jdk:
  - oraclejdk8

script: mvn install jacoco:report coveralls:report -DskipDocker
#script: mvn install -DskipTests=true -DskipDocker
