language: java

services:
  - docker

before_install:
  - mkdir /home/travis/data
  - docker run -v /home/travis/data:/data/db --name mongo -p 28001:27017 -d mongo

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -DskipDocker -Dskip.findbugs=true -Dpmd.skip=true -Dcheckstyle.skip=true -B -V > /dev/null 2>&1

jdk:
  - oraclejdk8

#script: mvn install jacoco:report coveralls:report
script:
  - docker ps --all
  - mvn install -DskipTests=true
  - docker ps --all
