language: java

services:
  - docker

before_install:
  - mkdir /home/travis/data
  - docker run -v /home/travis/data:/data/db --name mongo -p 28001:27017 -d mongo

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -DskipDocker -B -V

jdk:
  - oraclejdk8

#script: mvn install jacoco:report coveralls:report -DskipDocker
script: mvn install -DskipTests=true
