branches:
  except: master

language: java

services:
  - docker

addons:
  firefox: "49.0.2"
  sauce_connect:
    username: dickschoeller
  jwt:
    secure: "SCAjXGKQ5p6fZj38LFzYBursOm8HSNwkEHhbMQa8uVmRoH9lSzjr6HdeZLUFRUgKlttoI5xH21bo7ysw2Tshn6fvIZHnoWid23OniZF87aUs3OnwCGB5/vwFgU4K48juoDgJXc0IpgfH7rj8t5yCUEpP1jst3LJGmyTbUfOBSbzROS4UufwsKZdKNKXJbGN21d8q7dpAjUjD8OUgK834Nkj/973DiOVUcFBpF1FFf02yFDj0XJJITFiABDLEhZ1SgolKXCWRoFTruZKO3+OnycaZUUsICmuOj/3L7Aq1qQcUczJYZq0kCEHY6tQlXQrjepSGCh21GmuBCHHnMso8YMiC9szqVeAbP8/aFXCitlvw5q6Zw1GpHuk0bBwWJsZU5n2HTpTUKpMwGFGcdg3AQ6dFjwCpig3+D1HZJkHYaJRLN3qVQmtNRyiLwcr9F2RQEqtqN9yOvj5iiohFE+7pLMgpy+6rj+36XTYaJlQRZLGbQPhaiznlpz/B4XrjbttNgZZPOfIy05L/rh6L/TpeaKkbrJReOuz0iut3qeoqPE6bIJ5FJ5Tu5MR2WiRf8CYkasxfA89kjCEvpqMt6ujBtil7A0ZO9f+koIJvjZlXHq02XvBKf34ZLj/yjf209FPe7Gdz6uVQzOTGMqiWOSs0G//9cC33cwQzk1mMnK3TckU="

env:
  global:
    - INTEGRATION_TEST_ARGS="--settings=./config/settings.xml -B -Ptravis-integration-test -Dspring.data.mongodb.port=28001 -Dgedbrowser.home=/home/travis/gedbrowser -Dgeoservice.keyfile=stub -Dgeoservice.backupfile=/home/travis/gedbrowser/geoservice-test-backup.json -Dselenium.timeout=45 -Dselenium.version=3.3.1"
    # REPOTOKEN
    - secure: "cSqCmrTZ20xqVkiG7sC3XR3JQxWAayaoQQe8zfc5nhf5oy3zOWxNU7KrpWVCfMVHIQcC50qqHyfXH1Z4qIs6T4+GgVpiUxLv6zLYSAk+TtX/5eJ1ER7ZHDrtrFTHB9NAEW95RfAp0Ee/7OjuwP8GLTPQ0F05TWrbY8RPZ8ecZcmgzNKFTjMuHPnQhVGkYdgU8UlYr3Y/+1/yox+e4wNzoA84HTh4Cmld3g7Yx5jOx5vg/uVNgYqbvQ3oCYB0nAQNc6vF8IX5XwIS7EKdzJXrzuvMWcDs5IQki2MmAoVHXuvYB6UB6GuZ2MvO6PFQUwaXY02hZ1W+2XeGB+jGhE3cam34riFAQVW1OnhiTArKMQK8SOLKPSHHsI3vjIHQLAhRKC2kRWShIq/i0pnUevgkN0etub/Jc1uUCvusLqYIR/NFvuauz7ywFqaXejvstVnYOXrx/hZQ10dE6Aha5W2uKCRfJlGsb7Iln5OAGsIfoZk/8tn2m8MebsBsUdutAjudFOKJz6e+0Sv0RpJgZCTtM/Fo7Bx+YldDQ7M/ofCqDnrocIhXFnma8d1qdZM/qmj+6kpnoNEGBTK8+Z+bXXKMOZcbPBkVVWcKiVPM0cES8ZDetkI3RoITPPlUiQIziX9FXCiWqiAqTRsDzpVUaDdPND/ZQgyU/ySpdoy4tOilNXI="
    # GPG_PASSPHRASE
    - secure: "bxrzTYVeLpxKcO37OTVBKlNgny2rE1A4B2/Yw5I/OnO0iS1hl3kIcIPw07LUXG83HGMpkK/xncIoG6UQgKZWHHLYKKSC9H0QIg9sb+catrlSGp6JHdga/Xa2prbcdw1CxvPphGm0FUSa8ZhsFJvSBgealGLkEZvnhUbHVhdx+TmL2DLAPdX1dUGoZvhOGYmjwcsRpKwbV4ByOo27A7uwdVSTSBJb0rU9Wef4yX5/RGODTxp0GRSIlHmzaRcnLACAsYVO5Wikb7o/Yg3l3mV56a2qwt7SKCTbeAWhi1hOb+GsJOCNvnCIZP2IBh+L3h9nYjheavzmhhZ+yKUAfr5Lh1by0wgEHHXZVvzfpRePBLDuw5v8zXcR1B8EeMVWv5bia+nOpkfbiGW6l3h1QO+6QSI6KT9MVy1GCALPMYQ47HMEOReNMNyz6MPiqMU7sZXP9HVS9LYZNCIPA5qIfKXQ55VyzGqqJWRw4B92kZp+No+O22A9m/hh8H2aRzNYRiJqDQf8l2bidq6vGqFSZp2/P8rXaCaCuKdo+tIfbxvTdZb7fznnY8UewVYT9dXgbUHUx9kGPTOarMjmrcH9wxaBFqR3DRSQPceZlQ7ZR9itJq4c5CxVRH2GZIOCNb7SmmQBAe4970EzvFVL1Xv/PT8Q7MEhUER+Oi5AAj2CmTQ13PU="
    # GPG_KEY_NAME
    - secure: "KVpOHU7Oy44evUDdcWwWvNWWf2EvWQBeC5xcEiObCPz09U8tKRz8pX8bqwM1B8kFrXBNfrALFVkpgkqbb0pVuWbrKjqXKby+r05JR2pe0wPp/228nrNaRyD2OoruvF1+AJyWquS2CiDt68MkfNF6eJNcptYDMZnv8Nr2vb+hZkUn10Fqek9NvWnAsWTjPANZdpQjPrHHScRvLVadkCMubYr6WA+CSptBwYw+Tc9/Qgm0FZPsnDH82zD79JIKRQlorTedwZ1HxRwKFuwL1R1FgQXGIEFXgkT9N4E+93pF6QoeKacRrJWEt8Pq52dWpBqvT/mECkSPQ4swtVpoFU2NboBrtDcTyndH9yDfk0Xl6ASBSuV1KLUF4fF2My4Pv+HhB4j9TayrHkOkxSVdBJFNuo/UTProj4RxfGd4Zjca1ia9rHTYViAfX6syM2yrG0/Sx1tdHoDaZtmm54eJBxYqmCZnzw2ve69heIgdgBuy5U5qJPeJw+KMZx57yPEUpz1tgOk8KufAFB1k3S/AkBrnBPEhxY5+ls0GR2hVZwNwUi5CHcfKv5VkMQs2yyYmqM/rDu7ls0FmeOkFVOFnojM2dEyvOnegMkpJRlEAhIjRg7GtiTRQSZArohxFqWGxJUS6JscxaUlP6VklHcI5IwlFCI47G2ZsvUHxpj40J+0taGA="
    # DOCKERUSER
    - secure: "PjikRww8S7H8xY1i6GSDfmpdcSE9fc0ZVkEcbuX8r2/PgJWqY2VyvAQjWpOTZrx/SmyY7WSb+yLZ8t44VdHIVSONjEmyNvtymxw+uscVEBYB2waH8pv0Fi24wNN6x6kCFfrh1IFqVOWlF+7rVIPansJCsL0iToWZFGbmZqBbe3aWQVeSz51bCKu9CisEo5kEtuIAi/lYUbVDnKgKVm4i0zDVLDxtFyuYR4juwg6a7/y3ckBwtdCxCcq2gdl91qcP4dajSkGHlEw2BZZVVvO0UPU7crewylq4YiINf9owDEi0ojwCfQrUWs5IHqm3sz34GWMgkzuc57dKyHfpK+lxaWGuJ0sQMKf6edv845VFkLCMyKw3lpoLwN4qUtXubVODL9t0pytxupwfT211V4s/YUbSNG8WeuNoOu0GdzqJFmruilq8X6bIHLRjiYniqdnqAc9XRfCOBOPef1MPAm9mrIAZP/wAwqeSrmn0ml2x9uogSvP4/m3guHmCuMHW3kZDc6nRzbTFxK24BUGf1WSLH0FKuDSSBV1xRqubY78UxbmGDsR0VEaZ2Mo+NgceCZGivQemprsG2ugthlfwDk5/DESdA7NvfyaDcEV1zUEtfuIkjnkw9btaE1SeDbhaG4jjbntY2UfsoLcpo6TJAXCyB1eHDI0SKDmEnwz87Vzrq08="
    # DOCKERPASS
    - secure: "Dwo5GJjdDeTAIhje4zIgb81s5TLvZnr/nsrkBxlJE7PnAKQnpe/UFUaqE60st4yZUuQwn84EvULRUlj2t6e2OgRj91QwaryNCWQmyCHh/3CqfhZPqAZ2M7ZMsS31TyB5HgiFBqTlOjbPUScjKEldptffVaU9DwUpvoyutoczNfmIw++gUCzAhudZd7QQNezW++dCRiWxcAW75n8br4bm2Uz3cMPI5dxnda74a5kwCvQBjoev/wxzVY1JDdNxOiNS3Qn2WmClMQ3PyLaIofIDfVhrQvRtlEPeevyH61uPLh/NwDuF0btNTAGNEtWFsKpC41WqfY/+gQNhTs8q4V1HFXuEExKQU0CjsepWbxlj7Sn7upearQRZuaxSXphasxsn525ebqPYyllslBopvruyDrkEucDJt303cTzE2gbTZRW+badlEWnBrwvWGeTtqgQSiYse3e0E95VxpPcU6BLnhiXmGBbE41sic9JQSV6lPskg6Oxr91pNKBTlU5UwZ05NzRSYu8MY0w96Wwfyk8mLn9BCkeJrVBFqJc0TCNNM1JTXPmmhr5fb6eePdza/BmOWK8eFjfoKHquyG4Qap6U1GiDCFcU/K1UfAWBzArajlWCZQfmF4xBSpWpsr8FXUYjX87EiF7eu2aK8IGQSMKVB2BlplDhYDWfnNXixMV7Suu0="
    # OSSRH_USER
    - secure: "I7kpYvDzSW8c/aitLg+xrTSTihCEmravYKiBHQd5uEfLUq4iF59jAntYyQZWiO2Hr4GjeVekq6XpMBloddcyfg9RIXWh36BZ6v+1HOTNaA1GqjDLFjGdNBX8zgp1M0tCKor3xM00rMn9XvUcJIYRX3DkPLCefzsoBum4XZEhcVWxppClz1fHgJ/m4Wuc9IX47XWjXOiWha5ACM0osTXgNGEcDDtXDxZV3L+WPeNurATURiKXaCSlYOVIvpVHYAMLga4IT65ia3croRA37+EksRunt5rlhm5F0q9h/GtgCDdUVCl6sRFlq2xjzq5Ff3EpE+p0NWOH/vcvxc6Nre/+qDtoqHbw2Vc9lmnGYw+LUuboGY3hnmbDsqpi1C3aklNPlLgjldQKQ75bi6iWwyFcQ1Gp0+WoQ84qH1xV+HtEcPi8W5HBnD+vyi3RveL44FJ9ttXFwzymmWbgGGNaTwePl+hhwcXp3jYpnAfvlp9pgsKmMnw12g+8WBd5c3NbKCX85NFbKpa3aTp5x5RbfYsmar+qqf1FreiXM0B5noksca1FG0iQCRlTQIwLcQRjQc9AX4MkSPCvu9rrP9vToIBFITjgIaVjZEknf3eNkNjGD96fS1im+56+So5wJmpASPJnVbIJM6Fui+VMZAF4jhUgOi7In7zwDgALKr0oFSbxs44="
    # OSSRH_PASS
    - secure: "QcYMf74iQ//5ahvbXcWqvj0pHz4RtvH/gZWV+uBuhDsuxGDjC6I0jN0X2ew35c2KR1gQJz1jXwxkveU1PH3NNgeq0dOOI7teMDkuULrVaptMzzjU6puJPreq3GCRVE6LSWeSObBfpSfAbGfzoeagXOuUR8wmgh73nKr0vyVPM6QdDewmbdMiSfIYRYRWw+bmMENqn9roehYEHX90L8ac1JSiMaxKkDdL1WFaL3o/9IwrTN9vIXYbklRny8s1Qa81cYHWEO/3jaDEuniDcZ9tw6hH2J0POjewh1cEZwmYbc2H4IGkqLCays7zqqjP7YT9W6JKY2cWLtdTD35Lgr4nOZ8Ned8gzoX2PjuZDi60wv0pddpstic6T8XK/YDd7tnJD0lzSFhOu8auaXpn93UZiroamN1ajW5SHfnmEXt6Dg8coF1/JmXEZfbPaU68LDdcnN8vep5m7mNaS83DlhIyircH95+iPWXyOe+FAW9sOXurc2NnJF4DgMHvcmHosWQtGIuItpnsIyXyfb/ZzKullJ9jLeF+MesCCLy8IFzCBYWf2BKMiNC76OOeE8QLtXi8rFPlQzy1545cvTIPC5nz/pWRwyZ2Vh/cFQILiu/Px0wj1B73TSsH+Neqoyuf9AqeV6ysjYylPys9TcBbmGwz8Yrg4jHFeeFFfkTB+xQRW3k="
    # GOOGLE_GEOCODING_KEY
    - secure: "vVh1Gab3sJdoAh+RZrRYbz8XlGCPX3WVvVSuqyRsMdKt1HT2ZJsOzshLDdnUeOGlkwZp+NQcvR3oB1MyFwj6DO92hxETl2eW+AXRMR9ZV09Rhsvg/ZfnR7FZIuo/tV6XtNLHucLqKgGWuETzmsmTlObor4Ovr4nRpwibU7qCQJUinAlEDh5F9Nt1Nl2+2yqdPAzUdht56RlRMhdBR9vFjDK6cRj75QtrBt2r9GjCnM0fdCTX/5/zBiDQ0dsrhFl1sWNASmRjKJHuidGCmwjIa87Fn1I1CZXIutxQ3iGIKKKQYOJQ+kXqfUMaX76nE+LJqQtNle4HrkzYN/OO2xECiqN4boJjf0GsufscAurJG2eOWVhbfB0nxqPyMU7zg9MdJ46jm6mQ4vRwSfu6iuoBB944rhRO+JHcUAf08D5/F//tmus6H9RCOqneSGmkqpYFAWSPnm+I4aOLzxk2IXyoPDl45VPBXEMo+VSSveGJ2aEjdYbLm4hDxvhy/rvIhJwhp59NnNEJHV2AAtyriL4f4dDTfa6uw7TzjdA6qU0SxskH0YJ0Ixp0bauRwQf3r4Vs6BdGvp11gtJvvRM0eHUYKIRue/Nl0YOWhM2kJH+3BNufkqkxddTHZE/2T7rPFvk9dNmp+VOQAZWX+ceV757jxj9XyrHZO9BEeGs5DvI7clM="
    # GOOGLE_MAPPING_KEY
    - secure: "sMdtSxE1udkKi1DQOEnMW/WG5HCXEieHzVuyRwdA6dnTHb5IQEDkv/cVpBQ/m+ufEcg/mezNHK+P1kWbs/Nynv17CdxTxOZYTRCtLKeAMl7ev7B36eEwoqfmyCyPbjeVHbljatJKSYKBjKluzTMFbsSonrQosoHMF30ynFRRYoF5EVKt1FSc2K+RZR29u1fzSAsqFLPAl7hq8uO2BVspNUBj5vDL93WWidZ941Su1M1l+LDlj0ZYeHAdrsjRdO88l2ElPdbaQzHFewF+gjbC8Tm+OkKuio+Z9I9/6WJ4fZsnPQNtX2n8CysvxUDB6glk9RRZV5bfsJbE0Yig3ckY4IBWgBopk6IiGgiV7i3F9HxsSz1Vim6EEjar3BUVGc3D03K5bHxafIdxroq7x8e/8GzmojFREdcxKKbKCpvv8s5pVczIE5yNLVpatrKZOc7uMMuK6JqK1vzL4U5Cm1Xr4d4njy73+Fxt8iI4AyJZoHn11PTlkR9mPHT/0gb3IKFSvuLomKQXU/lE46tGTH/OephCJM+alIKBI+7ORoIKspfCL4Q2Gh4XbSnkO7eya9UqpLjqoFja1ms8Mxa2YMM5KL9WOmGJBbu8JRRYzQF/kQcOxrH3bOua8MYjXMNCGeGrDL6/X6KDLgkTiwEndOHzw+TDjid6dY3OHGPq8CwMkXk="

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build
      before_install: ./config/before-install.sh
      install: ./config/install.sh
      before_script: ./config/before-script.sh
      script:
      - ./config/script.sh
      - ./config/before-deploy.sh
      - ./config/deploy.sh
    - stage: selenium test
      before_install: ./config/before-install.sh
      install: ./config/install.sh
      before_script: ./config/before-script.sh
      script: ./config/selenium-script.sh chrome linux
    - before_install: ./config/before-install.sh
      install: ./config/install.sh
      before_script: ./config/before-script.sh
      script: ./config/selenium-script.sh iexplore win8
    - before_install: ./config/before-install.sh
      install: ./config/install.sh
      before_script: ./config/before-script.sh
      script: ./config/selenium-script.sh MicrosoftEdge win10
    - before_install: ./config/before-install.sh
      install: ./config/install.sh
      before_script: ./config/before-script.sh
      script: ./config/selenium-script.sh chrome win10
    - before_install: ./config/before-install.sh
      install: ./config/install.sh
      before_script: ./config/before-script.sh
      script: ./config/selenium-script.sh firefox win8
# browser choices -  android, chrome, firefox, MicrosoftEdge, iexplore, safari,
#                    operablink, konqueror, "internet explorer", iPhone, iPad,
#                    iehta
# platform choices - xp, win7, win8, win8.1, win10, mac, "ox x 10.6",
#                    "os x 10.8", "os x 10.9", "os x 10.10", "os x 10.11",
#                    "macos 10.12", linux, android, ""
# Don't know how to do chrome on iphone or ipad
