gedbrowser:
    home: /var/lib/gedbrowser

server:
    servlet-path: /gedbrowser

logging:
    level:
        org:
            schoellerfamily: INFO

spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true

management:
    port: 8081
