package org.schoellerfamily.gedobject.datamodel.factory;

import org.schoellerfamily.gedbrowser.datamodel.Attribute;
import org.schoellerfamily.gedbrowser.datamodel.GedObject;
import org.schoellerfamily.gedbrowser.datamodel.ObjectId;

/* default */ class AttributeFactory extends AbstractGedObjectFactory {
    /** */
    /* default */ static final AttributeFactory ATTR_FACTORY = new AttributeFactory();

    /**
     * The list of short and long strings for standard attributes.
     */
    private static final String[][] ATTRIBUTE_PAIRS = {
            {"ATTRIBUTE", "Attribute"},
            {"ABBR", "Abbreviation"},
            {"ABSTRACTOR", "Abstractor"},
            {"ABT", "About"},
            {"ACTIVE", "Active"},
            {"ADDR", "Address"},
            {"ADOP", "Adopted"},
            {"ADBAP", "Adult Baptism"},
            {"AFN", "Ancestral File Number"},
            {"AFT", "After"},
            {"AGE", "Age"},
            {"ALIA", "Alias"},
            {"ANCE", "Generations of ancestors"},
            {"ANUL", "Anullment"},
            {"AUDIO", "Audio"},
            {"AUTH", "Author"},
            {"AUTHOR", "Author"},
            {"BAPM", "Baptism"},
            {"BARM", "Bar Mitzvah"},
            {"BASM", "Bat Mitzvah"},
            {"BEF", "Before"},
            {"BEGIN", "Begin"},
            {"BET", "Between"},
            {"BIRT", "Birth"},
            {"BOOK", "Book"},
            {"BRIS", "Bris Milah"},
            {"BURI", "Burial"},
            {"BUSINESS", "Business"},
            {"CANCELED", "Canceled"},
            {"CARD", "Card"},
            {"CAST", "Caste"},
            {"CAUS", "Cause"},
            {"CEME", "Cemetery"},
            {"CENS", "Census"},
            {"CENSUS", "Census"},
            {"CHAN", "Changed"},
            {"CHAR", "Character Set"},
            {"CHR", "Christening"},
            {"CHURCH", "Church"},
            {"COMPILER", "Compiler"},
            {"COMPLETED", "Completed"},
            {"CONF", "Confirmation"},
            {"COPY", "Copy"},
            {"COURT", "Court"},
            {"DEAT", "Death"},
            {"DESC", "Generations of descendants"},
            {"DEST", "Destination"},
            {"DIV", "Divorce"},
            {"DIVF", "Divorce Final"},
            {"DIVORCED", "Divorced"},
            {"DONE", "Done"},
            {"EDITOR", "Editor"},
            {"EDUC", "Education"},
            {"ELECTRONIC", "Electronic"},
            {"EMIG", "Emigration"},
            {"ENGA", "Engaged"},
            {"EVEN", "Event"},
            {"EXTRACT", "Extract"},
            {"FAMF", "Family file"},
            {"FATH", "Father"},
            {"FEMALE", "Female"},
            {"FICHE", "Fiche"},
            {"FILE", "File"},
            {"FILM", "Film"},
            {"FORM", "Format"},
            {"FOUND", "Found"},
            {"FROM", "From"},
            {"GEDC", "GEDCOM"},
            {"GODP", "Godparent"},
            {"GOVERNMENT", "Government"},
            {"GRAD", "Graduation"},
            {"HEIR", "Heir"},
            {"HISTORY", "History"},
            {"IMMI", "Immigration"},
            {"INFANT", "Infant"},
            {"INFORMANT", "Informant"},
            {"INTERVIEW", "Interview"},
            {"INTERVIEWER", "Interviewer"},
            {"ISSUE", "Issue"},
            {"ITEM", "Item"},
            {"JOURNAL", "Journal"},
            {"LANG", "Language"},
            {"LETTER", "Letter"},
            {"LINE", "Line"},
            {"LINEAGE", "Lineage"},
            {"MAGAZINE", "Magazine"},
            {"MALE", "Male"},
            {"MANUSCRIPT", "Manuscript"},
            {"MAP", "Map"},
            {"MARB", "Marriage Bans"},
            {"MARL", "Marriage License"},
            {"MARR", "Marriage"},
            {"MARRIED", "Married"},
            {"MEDI", "Media"},
            {"MEMBER", "Member"},
            {"MILITARY", "Military"},
            {"MOTH", "Mother"},
            {"NAMR", "Name (religious)"},
            {"NAMING", "Naming"},
            {"NAMS", "NAMS"},
            {"NATU", "Naturalized"},
            {"NCHI", "Number of Children"},
            {"NEWLINE", "Newline"},
            {"NEWSPAPER", "Newspaper"},
            {"NMR", "Not Married"},
            {"NUMBER", "Number"},
            {"OCCU", "Occupation"},
            {"ORDI", "Ordinance process flag"},
            {"ORDERED", "Ordered"},
            {"ORGANIZATION", "Organization"},
            {"ORIGINAL", "Original"},
            {"OTHER", "Other"},
            {"PAGE", "Page"},
            {"PERIODICAL", "Periodical"},
            {"PERSONAL", "Personal"},
            {"PHON", "Phone Number"},
            {"PHOTO", "Photograph"},
            {"PHOTOCOPY", "Photocopy"},
            {"PLANNED", "Planned"},
            {"PLOT", "Plot"},
            {"PROB", "Probate"},
            {"PROVED", "Proved"},
            {"PUBL", "Published"},
            {"QUAY", "Surety"},
            {"RECITED", "Recited"},
            {"REFN", "Reference Number"},
            {"RELI", "Religion"},
            {"REPO", "Repository"},
            {"RESI", "Residence"},
            {"RESN", "Restriction"},
            {"RETI", "Retired"},
            {"ROLE", "Role"},
            {"SEX", "Sex"},
            {"SINGLE", "Single"},
            {"SITE", "Site"},
            {"SOUND", "Sound"},
            {"SPOU", "Spouse"},
            {"SSN", "Social Security Number"},
            {"STILLBORN", "Stillborn"},
            {"SUBMITTED", "Submitted"},
            {"TEMP", "Temple code"},
            {"TEXT", "Text"},
            {"TIME", "Time"},
            {"TITL", "Title"},
            {"TO", "To"},
            {"TOKEN", "Token"},
            {"TOMBSTONE", "Tombstone"},
            {"TRADITION", "Tradition"},
            {"TRANSCRIBER", "Transcriber"},
            {"TRANSCRIPT", "Transcript"},
            {"TYPE", "Type"},
            {"UNDERSCORE", "Underscore"},
            {"UNICODE", "Unicode"},
            {"UNPUBLISHED", "Unpublished"},
            {"UNVEIL", "Headstone unveiled"},
            {"VERS", "Version"},
            {"VIDEO", "Video"},
            {"VITAL", "Vital"},
            {"WIDOWED", "Widowed"},
            {"WILL", "Will"},
            {"WITN", "Witness"},
            {"XREF", "Cross Reference"},
            {"RAW", null}
    };

    static {
        for (final String[] pair : ATTRIBUTE_PAIRS) {
            put(pair[0], pair[1], ATTR_FACTORY);
        }

    }

    @Override
    public GedObject create(final GedObject parent, final ObjectId xref, final String tag,
            final String tail) {
        return new Attribute(parent, tag, tail);
    }
}
